import rtconfig
from building import *

CPPDEFINES = []

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
cwd = GetCurrentDir()

src = Split('''
RISCV/env_Eclipse/handlers.c
RISCV/env_Eclipse/init.c
RISCV/env_Eclipse/your_printf.c
GD32VW55x_standard_peripheral/system_gd32vw55x.c
GD32VW55x_standard_peripheral/Source/gd32vw55x_gpio.c
GD32VW55x_standard_peripheral/Source/gd32vw55x_rcu.c
GD32VW55x_standard_peripheral/Source/gd32vw55x_exti.c
GD32VW55x_standard_peripheral/Source/gd32vw55x_eclic.c
GD32VW55x_standard_peripheral/Source/gd32vw55x_syscfg.c
GD32VW55x_standard_peripheral/Source/gd32vw55x_pmu.c
GD32VW55x_standard_peripheral/Source/gd32vw55x_rtc.c
GD32VW55x_standard_peripheral/Source/gd32vw55x_fmc.c
GD32VW55x_standard_peripheral/Source/gd32vw55x_trng.c
GD32VW55x_standard_peripheral/Source/gd32vw55x_cau.c
GD32VW55x_standard_peripheral/Source/gd32vw55x_cau_aes.c
GD32VW55x_standard_peripheral/Source/gd32vw55x_cau_des.c
GD32VW55x_standard_peripheral/Source/gd32vw55x_cau_tdes.c
GD32VW55x_standard_peripheral/Source/gd32vw55x_hau.c
GD32VW55x_standard_peripheral/Source/gd32vw55x_hau_sha_md5.c
''')

if GetDepend(['RT_USING_SERIAL']):
    src += ['GD32VW55x_standard_peripheral/Source/gd32vw55x_usart.c']

if GetDepend(['RT_USING_I2C']):
    src += ['GD32VW55x_standard_peripheral/Source/gd32vw55x_i2c.c']

if GetDepend(['RT_USING_SPI']):
    src += ['GD32VW55x_standard_peripheral/Source/gd32vw55x_spi.c']

if GetDepend(['RT_USING_ADC']):
    src += ['GD32VW55x_standard_peripheral/Source/gd32vw55x_adc.c']

if GetDepend(['RT_USING_HWTIMER']) or GetDepend(['RT_USING_PWM']):
    src += ['GD32VW55x_standard_peripheral/Source/gd32vw55x_timer.c']

if GetDepend(['RT_USING_RTC']):
    src += ['GD32VW55x_standard_peripheral/Source/gd32vw55x_rtc.c']
    src += ['GD32VW55x_standard_peripheral/Source/gd32vw55x_pmu.c']

if GetDepend(['RT_USING_WDT']):
    src += ['GD32VW55x_standard_peripheral/Source/gd32vw55x_wwdgt.c']
    src += ['GD32VW55x_standard_peripheral/Source/gd32vw55x_fwdgt.c']

if GetDepend(['BSP_USING_WLAN']):
    CPPDEFINES += ['BSP_USING_WLAN']

path = [
    cwd + '/RISCV/drivers',
    cwd + '/GD32VW55x_standard_peripheral',
    cwd + '/GD32VW55x_standard_peripheral/Include',]

group = DefineGroup('Libraries', src, depend = ['SOC_SERIES_GD32VW55x'], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
